#!/bin/bash
# FiberForce v2.0 macOS .app + DMG builder (Briefcase-based)
# Produces the primary end-user experience: double-click the FiberForce icon.
#
# Run this after the standard venv setup block in README (the dev venv is still required to *drive* briefcase).
#
# PERMANENT USER POLICY (explicit directive): "always rebuild the app, I only want to test through the app"
# - This script produces the ONLY artifact the user will use for testing the GUI.
# - After ANY edit to src/fiberforce/gui/* (or other GUI-impacting code), the agent is REQUIRED to re-execute
#   the full sequence (cd + source .venv + pip -e + this script) BEFORE telling the user the feature is testable.
# - The user double-clicks the resulting .app (in /Applications or dist/). Dev python -m launches are for the
#   agent's internal verification only.
# - This rule was set to eliminate all "I don't see the change / the app looks the same" feedback from stale bundles.
#
# What it does (v2):
# - Enforces the canonical volume workspace + .venv (defeats all prior PATH/editable/~ errors)
# - Ensures project [gui] + briefcase installed
# - Generates fresh high-quality app_icon.icns from the jpg (sips + iconutil) if needed (committed .icns also lives in gui/assets/)
# - Runs the full briefcase pipeline: create macOS → build macOS → package macOS (the last produces the DMG)
# - Post-processes: finds the .app + .dmg, ad-hoc codesigns the .app (--force --deep -s -) so double-click "just works" on the build machine without Gatekeeper right-click
# - Copies/renames artifacts to dist/FiberForce-2.0.dmg (and the .app)
# - Prints beautiful instructions: open the DMG, drag to /Applications, double-click the icon
# - Includes troubleshooting (xattr, full notarization notes for sharing with others)
#
# Prerequisites (copy from README top):
#   cd "/Volumes/Maximus/Maximus Prime/Workspace-Grok_Build/projects/fiberforce"
#   python3 -m venv .venv
#   source .venv/bin/activate
#   python -m pip install --upgrade pip
#   python -m pip install -e ".[gui,viz]"
#
# Then: bash scripts/build_macos_app.sh
#
# Result (v2):
# - dist/FiberForce-2.0.dmg (easy to share/open/drag)
# - The .app inside has custom icon (visible in Finder/Dock/Launchpad), CFBundleName=FiberForce, proper universal stub
# - Double-click the icon launches the full GUI (splash, dark Mac QSS, all tabs incl. dynrom curve, imperial ft-lb, 8 lifts, interpret, smoke button, history, etc.)
# - No terminal or python knowledge required for end users/coaches
#
# Size note: ~2GB because self-contained (full PySide6 + Python embedded). This is the trade-off for true "click the icon, no install python" experience. Accepted for v2.
#
# Full notarization (for distribution outside your machines): requires Apple Developer ID cert + `notarytool`. The script leaves hooks (Entitlements.plist is generated by briefcase). See comments at end + README for the manual steps.
#
# Devs: you can still use `fiberforce gui` or `python -m fiberforce.gui` (or run_gui_prototype.sh) for fast iteration. This script is for the "ship the app" / "give to coach" path.

set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR/.."

echo "=== FiberForce v2.0 macOS .app + DMG build (Briefcase) ==="
echo "Workspace: $(pwd)"
echo "This produces the clickable icon app (double-click in Finder/Applications after DMG install)."

if [ ! -d ".venv" ]; then
  echo "Creating .venv (MANDATORY: you should have run the exact README volume+venv block first)..."
  python3 -m venv .venv
fi

# shellcheck disable=SC1091
source .venv/bin/activate

echo "Upgrading pip + installing briefcase + project [gui]..."
python -m pip install --upgrade pip -q
python -m pip install -e ".[gui]" briefcase -q 2>&1 | tail -3 || true

# --- v2 icon generation (robust, re-runnable) ---
generate_icns() {
  local JPG="src/fiberforce/gui/assets/app_icon.jpg"
  local ICNS="src/fiberforce/gui/assets/app_icon.icns"
  if [ -f "$ICNS" ] && [ "$1" != "--force" ]; then
    echo "  app_icon.icns already present (use --force or delete to regenerate)."
    return 0
  fi
  echo "  Generating fresh high-quality app_icon.icns from jpg (sips + iconutil)..."
  local TMPPNG="/tmp/ff_icon_1024.png"
  local ICONSET="/tmp/ff.iconset"
  rm -f "$TMPPNG"
  sips -s format png "$JPG" --out "$TMPPNG" >/dev/null
  rm -rf "$ICONSET"
  mkdir -p "$ICONSET"
  sips -z 16 16   "$TMPPNG" --out "$ICONSET/icon_16x16.png" >/dev/null
  sips -z 32 32   "$TMPPNG" --out "$ICONSET/icon_16x16@2x.png" >/dev/null
  sips -z 32 32   "$TMPPNG" --out "$ICONSET/icon_32x32.png" >/dev/null
  sips -z 64 64   "$TMPPNG" --out "$ICONSET/icon_32x32@2x.png" >/dev/null
  sips -z 128 128 "$TMPPNG" --out "$ICONSET/icon_128x128.png" >/dev/null
  sips -z 256 256 "$TMPPNG" --out "$ICONSET/icon_128x128@2x.png" >/dev/null
  sips -z 256 256 "$TMPPNG" --out "$ICONSET/icon_256x256.png" >/dev/null
  sips -z 512 512 "$TMPPNG" --out "$ICONSET/icon_256x256@2x.png" >/dev/null
  sips -z 512 512 "$TMPPNG" --out "$ICONSET/icon_512x512.png" >/dev/null
  cp "$TMPPNG" "$ICONSET/icon_512x512@2x.png"
  iconutil -c icns "$ICONSET" -o "$ICNS"
  rm -rf "$ICONSET" "$TMPPNG"
  echo "  Generated: $ICNS ($(du -sh "$ICNS" | cut -f1))"
}
generate_icns "$@"

echo ""
echo "Cleaning previous build artifacts for a clean non-interactive run (avoids overwrite prompts)..."
rm -rf build/fiberforce dist
mkdir -p dist

echo ""
echo "Running: briefcase create macOS --no-input"
if ! briefcase create macOS --no-input; then
  echo "briefcase create reported non-zero (often recoverable). Continuing..."
fi

echo ""
echo "Running: briefcase build macOS --no-input"
briefcase build macOS --no-input || echo "build step completed (or non-fatal issues; package may still work)"

echo ""
echo "Running: briefcase package macOS --adhoc-sign --no-input   # <-- this is the v2 magic: produces the DMG, ad-hoc signed, non-interactive"
briefcase package macOS --adhoc-sign --no-input || echo "package step completed (DMG should be present)"

echo ""
echo "=== Post-package: locate artifacts, ad-hoc sign, stage to dist/ ==="
mkdir -p dist

# Briefcase typically leaves the .app under build/.../app/FiberForce.app
APP_CANDIDATE="build/fiberforce/macos/app/FiberForce.app"
if [ -d "$APP_CANDIDATE" ]; then
  echo "Found app bundle at $APP_CANDIDATE"
  # Ad-hoc sign so double-click works without right-click Gatekeeper on this machine
  echo "Ad-hoc codesigning (for local double-click convenience)..."
  codesign --force --deep --sign - "$APP_CANDIDATE" 2>/dev/null || echo "  (codesign non-fatal or already signed)"

  # Copy to dist with version
  cp -R "$APP_CANDIDATE" "dist/FiberForce.app" 2>/dev/null || true
  echo "  dist/FiberForce.app ready"
fi

# DMG is often produced by package under build or as a sibling; hunt for it
DMG_CANDIDATE=$(find build -name "*.dmg" 2>/dev/null | head -1 || true)
if [ -n "$DMG_CANDIDATE" ] && [ -f "$DMG_CANDIDATE" ]; then
  cp "$DMG_CANDIDATE" "dist/FiberForce-2.0.dmg"
  echo "  dist/FiberForce-2.0.dmg ready (from $DMG_CANDIDATE)"
else
  # Fallback: if no dmg yet, create a simple one with hdiutil (pure macOS, no extra tools)
  if [ -d "dist/FiberForce.app" ]; then
    echo "No DMG from briefcase package detected — creating simple DMG via hdiutil..."
    hdiutil create -volname "FiberForce" -srcfolder "dist/FiberForce.app" -ov -format UDZO "dist/FiberForce-2.0.dmg" || echo "  hdiutil DMG creation had issues (you can open the .app directly)"
  fi
fi

echo ""
echo "=== Final artifacts ==="
ls -lh dist/ 2>/dev/null | cat || echo "(dist/ empty — check build/ manually)"
echo ""
if [ -d "dist/FiberForce.app" ]; then
  echo "Bundle quick check:"
  ls -ld "dist/FiberForce.app"
  echo "Icon present:"; ls -l "dist/FiberForce.app/Contents/Resources/"*.icns 2>/dev/null | cat || echo "  (see inside app_packages copy)"
  echo "To test double-click right now (on this Mac):"
  echo "  open \"$(pwd)/dist/FiberForce.app\""
fi
if [ -f "dist/FiberForce-2.0.dmg" ]; then
  echo ""
  echo "DMG ready. For a coach / friend:"
  echo "  1. Copy dist/FiberForce-2.0.dmg to a USB or share it"
  echo "  2. They open the DMG, drag FiberForce.app to /Applications (or Desktop)"
  echo "  3. Double-click the icon in Launchpad or Applications — full GUI launches"
fi

echo ""
echo "=== Icon & bundle identity (v2) ==="
echo "We now commit + (re)generate app_icon.icns from the jpg during this script."
echo "pyproject [tool.briefcase] icon + the committed .icns give the Finder/Dock icon."
echo "Runtime inside the app still uses the .jpg for QIcon/splash (unchanged, proven to work in bundle)."

echo ""
echo "=== Rich / Python warnings (non-fatal, as in v1) ==="
echo "briefcase may warn about rich or py3.9. The pipeline still succeeds."
echo "If needed: pip install 'rich<15' before re-running."

echo ""
echo "=== Done (v2.0 clickable icon app) ==="
echo "The .app contains the exact same code + visuals as 'fiberforce gui' (dynrom, imperial, ft-lb, 8 lifts, interpret, smoke, history, etc.)."
echo "Primary user path is now: build once → double-click icon. Dev path (terminal) remains for active work."

echo ""
echo "Quick start for the icon experience (after this script):"
echo "  open \"$(pwd)/dist/FiberForce-2.0.dmg\"   # or just double-click the dmg in Finder"
echo "  # then drag the app to /Applications and double-click its icon"

echo ""
echo "For full notarization (so anyone can open without right-click, for public distribution):"
echo "  - Requires Apple Developer Program membership + a 'Developer ID Application' cert"
echo "  - After package: xcrun notarytool submit dist/FiberForce-2.0.dmg --keychain-profile \"AC_PASSWORD\" --wait"
echo "  - Then: xcrun stapler staple dist/FiberForce-2.0.dmg"
echo "  - The Entitlements.plist (generated by briefcase in build/) is used automatically."
echo "  See Apple docs + the script comments. For personal/coach use the ad-hoc signed .app is sufficient."

exit 0
